---
- name: apply common configuration to all nodes
  hosts: hetzner-vm
  user: root
  become: yes
  gather_facts: no
  vars:
    - okd_domain: "DOMAIN.ch"
    - okd_admin_username: "USER"
    - okd_admin_password: "PASSWORD"
    - okd_api_port: "8443"

  roles:
    - { role: "common", tags: "common" }
