---
- name: apply common configuration to all nodes
  hosts: hetzner-vm
  user: root
  become: yes
  gather_facts: no
  vars: 
    - okd_domain: "YOUR_DOMAIN"
    - okd_admin_username: "YOUR_ADMIN_USER"
    - okd_admin_password: "YOUR_ADMIN_USER_PASSWORD"
    - okd_api_port: "8443"

  roles:
    - { role: "common", tags: "common" }
