---
- name: apply common configuration to all nodes
  hosts: hetzner-vm
  user: root
  become: yes
  gather_facts: no
  vars:
    - okd_domain: "c3smonkey.ch"
    - okd_admin_username: "monkey"
    - okd_admin_password: "monkeyPassword"
    - okd_api_port: "8443"

  roles:
    - { role: "common", tags: "common" }
