---
- name: apply common configuration to all nodes
  hosts: hetzner-vm
  user: root
  become: yes
  gather_facts: no
  vars:
    - okd_domain: "keepcalm.ch"
    - okd_admin_username: "john"
    - okd_admin_password: "Welcome1_"
    - okd_api_port: "8443"

  roles:
    - { role: "common", tags: "common" }
    
