---
- name: Install Git applications
  yum:
    name: git
    state: latest

- name: Check Git version
  command: git version

- name: Clone OKD installation repository
  ignore_errors: yes
  command: git clone https://github.com/okd-community-install/installcentos.git

- name: Transfer the installation script
  copy: src=install-openshift.sh dest=$HOME/installcentos/ mode=0777

# - name: Download install-openshift.sh script from GitHub
#   shell: |
#        curl https://raw.githubusercontent.com/gshipley/installcentos/master/install-openshift.sh  --output $HOME/installcentos/install-openshift.sh

- name: Install OKD on Hetzner
  shell: |
    cd $HOME/installcentos/

    export PVS=true
    export DOMAIN={{okd_domain}}
    export USERNAME={{okd_admin_username}}
    export PASSWORD={{okd_admin_password}}
    export API_PORT={{okd_api_port}}
    export INTERACTIVE="false"

    ./install-openshift.sh > install.log

- name: Read installation log file
  shell: |
        cat $HOME/installcentos/install.log
