---
- name: Install Git applications
  yum:
    name: git
    state: latest

- name: Check Git version
  command: git version

- name: Clone OKD installation repository
  ignore_errors: yes
  command: git clone https://github.com/gshipley/installcentos.git

- name: Change to OKD installation repository
  command: cd installcentos

- name: Download install script from GitHub
  shell: |
       curl https://raw.githubusercontent.com/gshipley/installcentos/master/install-openshift.sh  --output $HOME/installcentos/install-openshift.sh

- name: Update Install Script with 
  lineinfile:
    dest: /$HOME/installcentos/install-openshift.sh
    line: "{{ item.line }}"
    insertafter: '#!/bin/bash'
  with_items:
    - {  line: 'export PASSWORD="{{okd_admin_password}}"' }
    - {  line: 'export USERNAME="{{okd_admin_username}}"' }
    - {  line: 'export DOMAIN="{{okd_domain}}"' }
  
- name: Install Openshift
  shell: |
       /$HOME/installcentos/install-openshift.sh | INTERACTIVE=false /bin/bash
